--Task01
ALTER TABLE TEACHER
ADD
(BIRTHDAY DATE,
SALARY INT);

DELETE FROM TEACHER;
 
INSERT INTO TEACHER
VALUES ('СМЛВ', 'Смелов Владимир Владиславович', 'ИСиТ', '19.02.2011', 100);

INSERT INTO TEACHER
VALUES ('АКНВЧ', 'Акунович Станислав Иванович', 'ИСиТ', '13.03.2019', 700);

INSERT INTO TEACHER
VALUES ('КЛСНВ', 'Колесников Леонид Валерьевич', 'ИСиТ', '03.05.2009', 500);

INSERT INTO TEACHER
VALUES ('ГРМН', 'Герман Олег Витольдович', 'ИСиТ', '27.08.2015', 800);

INSERT INTO TEACHER
VALUES ('ЛЩНК', 'Лащенко Анатолий Пвалович', 'ИСиТ', '01.07.2018', 400);

INSERT INTO TEACHER
VALUES ('БРКВЧ', 'Бракович Андрей Игорьевич', 'ИСиТ', '09.06.1999', 500);

INSERT INTO TEACHER
VALUES ('ДДК', 'Дедко Александр Аркадьевич', 'ИСиТ', '07.12.2001', 700);

INSERT INTO TEACHER
VALUES ('КБЛ', 'Кабайло Александр Серафимович', 'ИСиТ', '17.03.2004', 900);

INSERT INTO TEACHER
VALUES ('УРБ', 'Урбанович Павел Павлович', 'ИСиТ', '24.04.2004', 600);

INSERT INTO TEACHER
VALUES ('РМНК', 'Романенко Дмитрий Михайлович', 'ИСиТ', '09.04.1967', 400);

INSERT INTO TEACHER
VALUES ('ПСТВЛВ', 'Пустовалова Наталия Николаевна', 'ИСиТ', '20.07.2007', 300);

INSERT INTO TEACHER
VALUES ('ГРН', 'Гурин Николай Иванович', 'ИСиТ', '24.12.1993', 400);

INSERT INTO TEACHER
VALUES ('ЖЛК', 'Жиляк Надежда Александровна', 'ИСиТ', '21.04.2001', 1000);

INSERT INTO TEACHER
VALUES ('БРТШВЧ', 'Барташевич Святослав Александрович', 'ПОиСОИ', '19.07.1984', 900);

INSERT INTO TEACHER
VALUES ('ЮДНКВ', 'Юденков Виктор Степанович', 'ПОиСОИ', '03.02.2001', 800);

INSERT INTO TEACHER
VALUES ('БРНВСК', 'Барановский Станислав Иванович', 'ЭТиМ', '29.01.2009', 500);

INSERT INTO TEACHER
VALUES ('НВРВ', 'Неверов Александр Васильевич', 'МиЭП', '28.04.2001', 100);

INSERT INTO TEACHER
VALUES ('РВКЧ', 'Ровкач Андрей Иванович', 'ОВ', '20.08.2002', 300);

INSERT INTO TEACHER
VALUES ('ДМДК', 'Демидко Марина Николаевна', 'ЛПиСПС', '09.02.2001', 500);

INSERT INTO TEACHER
VALUES ('МШКВСК', 'Машковский Владимир Петрович', 'ЛУ', '25.07.2005', 700);

INSERT INTO TEACHER
VALUES ('ЛБХ', 'Лабоха Константин Валентинович', 'ЛВ', '05.05.1986', 800);

INSERT INTO TEACHER
VALUES ('ЗВГЦВ', 'Звягинцев Вячеслав Борисович', 'ЛЗиДВ', '12.11.1999', 400);

INSERT INTO TEACHER
VALUES ('БЗБРДВ', 'Безбородов Владимир Степанович', 'ОХ', '16.04.2003', 500);

INSERT INTO TEACHER
VALUES ('ПРКПЧК', 'Прокопчук Николай Романович', 'ТНХСиППМ', '19.02.2001', 800);

INSERT INTO TEACHER
VALUES ('НСКВЦ', 'Насковец Михаил Трофимович', 'ТЛ', '12.11.1988', 900);

INSERT INTO TEACHER
VALUES ('МХВ', 'Мохов Сергей Петрович', 'ЛМиЛЗ', '02.01.2009', 1200);

INSERT INTO TEACHER
VALUES ('ЕЩНК', 'Ещенко Людмила Семеновна', 'ТНВиОХТ', '16.05.2003', 1000);

INSERT INTO TEACHER
VALUES ('ЖРСК', 'Жарский Иван Михайлович', 'ХТЭПиМЭЕ', '13.11.2002', 400);

SELECT * FROM TEACHER;


--Task02
DECLARE
    CURSOR TEACHER_CURSOR IS
    SELECT TEACHER_NAME FROM TEACHER;
    TEACHER_NAME TEACHER.TEACHER_NAME%TYPE;
BEGIN
    OPEN TEACHER_CURSOR;
    FETCH TEACHER_CURSOR INTO TEACHER_NAME;
    WHILE TEACHER_CURSOR%FOUND
    LOOP
        DBMS_OUTPUT.PUT_LINE(
        SUBSTR(TEACHER_NAME, 1, INSTR(TEACHER_NAME, ' ') - 1)
        || ' ' || SUBSTR(TEACHER_NAME, INSTR(TEACHER_NAME, ' ') + 1, 1)
        || '.' || SUBSTR(TEACHER_NAME, INSTR(TEACHER_NAME, ' ', 1, 2) + 1, 1) || '.');
        FETCH TEACHER_CURSOR INTO TEACHER_NAME;
    END LOOP;
    CLOSE TEACHER_CURSOR;
END;


--Task03
DECLARE
    CURSOR TEACHER_CURSOR IS
    SELECT TEACHER_NAME, BIRTHDAY FROM TEACHER;
    TEACHER_NAME TEACHER.TEACHER_NAME%TYPE;
    BIRTHDAY TEACHER.BIRTHDAY%TYPE;
BEGIN
    OPEN TEACHER_CURSOR;
    FETCH TEACHER_CURSOR INTO TEACHER_NAME, BIRTHDAY;
    WHILE TEACHER_CURSOR%FOUND
    LOOP
        IF NEXT_DAY(BIRTHDAY, 'ПОНЕДЕЛЬНИК') = BIRTHDAY + 7 THEN 
            DBMS_OUTPUT.PUT_LINE(TEACHER_NAME || ' --> ' || BIRTHDAY);
        END IF;
            FETCH TEACHER_CURSOR INTO TEACHER_NAME, BIRTHDAY;
    END LOOP;
    CLOSE TEACHER_CURSOR;
END;


--Task04
DECLARE
    CURSOR TEACHER_CURSOR IS
    SELECT TEACHER_NAME, BIRTHDAY FROM TEACHER;
    TEACHER_NAME TEACHER.TEACHER_NAME%TYPE;
    BIRTHDAY TEACHER.BIRTHDAY%TYPE;
    NEXT_MONTH VARCHAR2(2) := SUBSTR(ADD_MONTHS(CURRENT_DATE, 1), 4, 2);
BEGIN
    
    OPEN TEACHER_CURSOR;
    FETCH TEACHER_CURSOR INTO TEACHER_NAME, BIRTHDAY;
    WHILE TEACHER_CURSOR%FOUND
    LOOP
        IF EXTRACT(MONTH FROM BIRTHDAY) = NEXT_MONTH THEN
            DBMS_OUTPUT.PUT_LINE(TEACHER_NAME || ' --> ' || BIRTHDAY);
        END IF;
        FETCH TEACHER_CURSOR INTO TEACHER_NAME, BIRTHDAY;
    END LOOP;
    CLOSE TEACHER_CURSOR;
END;

CREATE VIEW TEACHERS_WITH_BIRTHDAY_IN_NEXT_MONTH AS SELECT TEACHER_NAME, BIRTHDAY FROM TEACHER 
WHERE EXTRACT(MONTH FROM BIRTHDAY) = SUBSTR(ADD_MONTHS(CURRENT_DATE, 1), 4, 2);
SELECT * FROM TEACHERS_WITH_BIRTHDAY_IN_NEXT_MONTH;
DROP VIEW TEACHERS_WITH_BIRTHDAY_IN_NEXT_MONTH;


--Task05
DROP VIEW COUNT_MONTH;

CREATE VIEW COUNT_MONTH AS
SELECT
    SUM(CASE WHEN EXTRACT(MONTH FROM BIRTHDAY) = 1 THEN 1 ELSE 0 END) "ЯНВАРЬ", 
    SUM(CASE WHEN EXTRACT(MONTH FROM BIRTHDAY) = 2 THEN 1 ELSE 0 END) "ФЕВРАЛЬ", 
    SUM(CASE WHEN EXTRACT(MONTH FROM BIRTHDAY) = 3 THEN 1 ELSE 0 END) "МАРТ", 
    SUM(CASE WHEN EXTRACT(MONTH FROM BIRTHDAY) = 4 THEN 1 ELSE 0 END) "АПРЕЛЬ", 
    SUM(CASE WHEN EXTRACT(MONTH FROM BIRTHDAY) = 5 THEN 1 ELSE 0 END) "МАЙ", 
    SUM(CASE WHEN EXTRACT(MONTH FROM BIRTHDAY) = 6 THEN 1 ELSE 0 END) "ИЮНЬ", 
    SUM(CASE WHEN EXTRACT(MONTH FROM BIRTHDAY) = 7 THEN 1 ELSE 0 END) "ИЮЛЬ", 
    SUM(CASE WHEN EXTRACT(MONTH FROM BIRTHDAY) = 8 THEN 1 ELSE 0 END) "АВГУСТ", 
    SUM(CASE WHEN EXTRACT(MONTH FROM BIRTHDAY) = 9 THEN 1 ELSE 0 END) "СЕНТЯБРЬ", 
    SUM(CASE WHEN EXTRACT(MONTH FROM BIRTHDAY) = 10 THEN 1 ELSE 0 END) "ОКТЯБРЬ", 
    SUM(CASE WHEN EXTRACT(MONTH FROM BIRTHDAY) = 11 THEN 1 ELSE 0 END) "НОЯБРЬ", 
    SUM(CASE WHEN EXTRACT(MONTH FROM BIRTHDAY) = 12 THEN 1 ELSE 0 END) "ДЕКАБРЬ"
FROM TEACHER;
SELECT * FROM COUNT_MONTH;


--Task06
DECLARE
CURSOR TEACHER_CURSOR IS
    SELECT TEACHER_NAME, BIRTHDAY FROM TEACHER;
    TEACHER_NAME TEACHER.TEACHER_NAME%TYPE;
    BIRTHDAY TEACHER.BIRTHDAY%TYPE;
BEGIN
    OPEN TEACHER_CURSOR;
    FETCH TEACHER_CURSOR INTO TEACHER_NAME, BIRTHDAY;
    WHILE TEACHER_CURSOR%FOUND
    LOOP
        IF MOD(TO_NUMBER(EXTRACT(YEAR FROM BIRTHDAY)) + 1, 5) = 0 THEN 
            DBMS_OUTPUT.PUT_LINE(TEACHER_NAME || ' --> ' || BIRTHDAY); 
        END IF;
        FETCH TEACHER_CURSOR INTO TEACHER_NAME, BIRTHDAY;
    END LOOP;
    CLOSE TEACHER_CURSOR;
END;


--Task07
DECLARE
    CURSOR TEACHER_CURSOR IS 
    SELECT F.FACULTY, SUM(SALARY) / COUNT(T.PULPIT) FROM TEACHER T
    INNER JOIN PULPIT P
    ON P.PULPIT = T.PULPIT
    INNER JOIN FACULTY F
    ON F.FACULTY = P.FACULTY
    GROUP BY F.FACULTY;
    
    FACULTY PULPIT.FACULTY%TYPE;
    AVG_SALARY_AT_FACULTY FLOAT;
    AMOUNT_OF_FACULTIES INT := 0;
    AVG_SALARY_AT_ALL_FACULTIES FLOAT := 0;
BEGIN
    OPEN TEACHER_CURSOR;
    FETCH TEACHER_CURSOR INTO FACULTY, AVG_SALARY_AT_FACULTY;
    WHILE TEACHER_CURSOR%FOUND
    LOOP
        AMOUNT_OF_FACULTIES := AMOUNT_OF_FACULTIES + 1;
        AVG_SALARY_AT_ALL_FACULTIES := AVG_SALARY_AT_ALL_FACULTIES + AVG_SALARY_AT_FACULTY;
        DBMS_OUTPUT.PUT_LINE(RTRIM(FACULTY) || ' -> AVERAGE SALARY: ' || FLOOR(AVG_SALARY_AT_FACULTY)); 
        FETCH TEACHER_CURSOR INTO FACULTY, AVG_SALARY_AT_FACULTY;
    END LOOP;
    CLOSE TEACHER_CURSOR;
    DBMS_OUTPUT.PUT_LINE('AVGERAGE SALARY AT ALL FACULTIES: ' || FLOOR(AVG_SALARY_AT_ALL_FACULTIES / AMOUNT_OF_FACULTIES)); 
END;

--Task08
DECLARE
    TYPE PERSON IS RECORD
    (
        NAME VARCHAR2(20),
        AGE INT
    );
    PERSON1 PERSON;
    PERSON2 PERSON;
BEGIN
    PERSON1.NAME := 'Maksim';
    PERSON1.AGE := 19;
    DBMS_OUTPUT.PUT_LINE(PERSON1.NAME || ' ' ||PERSON1.AGE);
END;
