DROP DATABASE LINK chypris;
CREATE DATABASE LINK chypris
CONNECT TO SYSTEM
IDENTIFIED BY oracle
USING '(DESCRIPTION =
(ADDRESS_LIST =
  (ADDRESS = (PROTOCOL = TCP)(HOST = 172.20.10.1)(PORT = 1521))
)
(CONNECT_DATA =
  (SERVICE_NAME = orcl)
)
)';
SELECT * FROM BAN@chypris;