--Task01
CREATE TABLE T_RANGE
(
    SOME_NUMBER NUMBER
)
PARTITION BY RANGE (SOME_NUMBER)
(
    PARTITION RANGE1 VALUES LESS THAN (10),
    PARTITION RANGE2 VALUES LESS THAN (20),
    PARTITION RANGE3 VALUES LESS THAN (MAXVALUE)
);


--Task02
CREATE TABLE T_INTERVAL
(
    SOME_DATE DATE
)
PARTITION BY RANGE(SOME_DATE)
INTERVAL (NUMTOYMINTERVAL (1, 'YEAR'))
(
    PARTITION INTERVAL1 VALUES LESS THAN ('01.01.2015')
);


--Task03
CREATE TABLE T_HASH
(
    SOME_STRING VARCHAR2(15)
)
PARTITION BY HASH(SOME_STRING) PARTITIONS 16


--Task04
CREATE TABLE T_LIST
(
    SOME_STRING CHAR(15)
)
PARTITION BY LIST (SOME_STRING)
(
    PARTITION X1 VALUES('A'),
    PARTITION X2 VALUES('AA'),
    PARTITION X3 VALUES(DEFAULT)
);


--Task05
INSERT INTO T_RANGE VALUES(5);
INSERT INTO T_RANGE VALUES(15);
INSERT INTO T_RANGE VALUES(42);
SELECT * FROM T_RANGE;
SELECT * FROM T_RANGE PARTITION (RANGE1);
SELECT * FROM T_RANGE PARTITION (RANGE2);
SELECT * FROM T_RANGE PARTITION (RANGE3);


INSERT INTO T_INTERVAL VALUES('05.01.2015');
INSERT INTO T_INTERVAL VALUES('25.03.2018');
SELECT * FROM T_INTERVAL;
SELECT * FROM T_INTERVAL PARTITION FOR ('05.05.2018');
SELECT * FROM T_INTERVAL PARTITION FOR ('20.01.2015');


INSERT INTO T_HASH VALUES('HELLO');
INSERT INTO T_HASH VALUES('WORLD');
INSERT INTO T_HASH VALUES('!!!');
SELECT * FROM T_HASH;


INSERT INTO T_LIST VALUES('B');
INSERT INTO T_LIST VALUES('ASD');
INSERT INTO T_LIST VALUES('AA');
INSERT INTO T_LIST VALUES('A');
SELECT * FROM T_LIST;
SELECT * FROM T_LIST PARTITION (X1);
SELECT * FROM T_LIST PARTITION (X3);


--Task06
ALTER TABLE T_RANGE ENABLE ROW MOVEMENT;
UPDATE T_RANGE PARTITION(RANGE2)
SET SOME_NUMBER = SOME_NUMBER - 5;


--Task07
ALTER TABLE T_LIST MERGE PARTITIONS
X1, X2 INTO PARTITION X12;


--Taskk08
ALTER TABLE T_RANGE SPLIT PARTITION RANGE1
AT (8) INTO
(
    PARTITION RANGE1A,
    PARTITION RANGE1B
);


--Task09
CREATE TABLE ZZZ
(
    Z NUMBER
);

ALTER TABLE T_RANGE EXCHANGE PARTITION RANGE3
WITH TABLE ZZZ WITHOUT VALIDATION;

SELECT * FROM ZZZ




